export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 99.99,
    rating: 4.5,
    category: "Electronics",
    image: "/placeholder.svg?height=200&width=200",
    description: "Premium wireless headphones with noise cancellation",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 199.99,
    rating: 4.8,
    category: "Electronics",
    image: "/placeholder.svg?height=200&width=200",
    description: "Feature-rich smartwatch with health tracking",
  },
  {
    id: 3,
    name: "Laptop Stand",
    price: 29.99,
    rating: 4.2,
    category: "Accessories",
    image: "/placeholder.svg?height=200&width=200",
    description: "Ergonomic aluminum laptop stand",
  },
  {
    id: 4,
    name: "Coffee Maker",
    price: 79.99,
    rating: 4.6,
    category: "Home",
    image: "/placeholder.svg?height=200&width=200",
    description: "Programmable coffee maker with thermal carafe",
  },
  {
    id: 5,
    name: "Yoga Mat",
    price: 24.99,
    rating: 4.3,
    category: "Fitness",
    image: "/placeholder.svg?height=200&width=200",
    description: "Non-slip exercise yoga mat with carrying strap",
  },
  {
    id: 6,
    name: "Desk Lamp",
    price: 39.99,
    rating: 4.4,
    category: "Home",
    image: "/placeholder.svg?height=200&width=200",
    description: "LED desk lamp with adjustable brightness",
  },
  {
    id: 7,
    name: "Water Bottle",
    price: 19.99,
    rating: 4.7,
    category: "Fitness",
    image: "/placeholder.svg?height=200&width=200",
    description: "Insulated stainless steel water bottle",
  },
  {
    id: 8,
    name: "Wireless Mouse",
    price: 49.99,
    rating: 4.5,
    category: "Electronics",
    image: "/placeholder.svg?height=200&width=200",
    description: "Ergonomic wireless mouse with precision tracking",
  },
]

export const categories = ["All", "Electronics", "Accessories", "Home", "Fitness"]

